-- Optional: schedule birthday-telegram via pg_cron + pg_net.
-- Replace PROJECT_REF and paste your service role key carefully
-- (or prefer GitHub Actions — see .github/workflows/birthday-telegram.yml).
--
-- Enable extensions first (Database → Extensions): pg_cron, pg_net

-- select cron.unschedule('shajira-birthday-telegram');

-- select cron.schedule(
--   'shajira-birthday-telegram',
--   '5 * * * *',
--   $$
--   select net.http_post(
--     url := 'https://PROJECT_REF.supabase.co/functions/v1/birthday-telegram',
--     headers := jsonb_build_object(
--       'Content-Type', 'application/json',
--       'x-cron-secret', 'YOUR_TELEGRAM_CRON_SECRET'
--     ),
--     body := '{}'::jsonb
--   );
--   $$
-- );
